import type { NextPage } from 'next';
import Head from 'next/head';
import tw from 'twin.macro';

const DivWithBorder = tw.div`border border-red-400 max-w-[150px]`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <DivWithBorder>Hey</DivWithBorder>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
